server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**


        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/user/**


        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/product/**


        - id: category-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/category/**


        - id: stock-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/stock/**


        - id: cart-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/cart/**

        - id: cart-item-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/cart-item/**


        - id: order-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/order/**

        - id: order-item-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/order-item/**

        - id: payment-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/payment/**

        - id: address-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/address/**



secret:
  key: W9Eh9YZQKqSZuxQfgq68L+YRRJRyrn4i+QCdffMiMwXuNAycxUPBFw4C4rMkEgQ/+XhwRn2kTdZkyR70gGSroOAYwzXswihIaeMpLGNMcStZcAGwChwgIVg7hQrDMRRbq74l798+EO5qhVTeX/AlBvFEhm/m81P/RluPfg+kTUNSnXHPGbmUkODZ8sDxOlHkTK98H1V3FFjUjF6gif3lJNO/n0mB+uoX4cwjhHCZQHpONC5DKTNB3FyT7Xf0aoovxNDpMmXBpUKI0nm5zGAttdDOPeevZVdOS5oTfw+a2h5xW0zKSk5hjN35eRTLkGnJb5MC7YCIjWP9z4ELek+npA==
