server:
  port: 8088

spring:
  application:
    name: payment-service
  rabbitmq:
      host: localhost      # Docker kullanmıyorsanız, RabbitMQ localhost üzerinde çalışıyor.
      port: 5672
      username: guest
      password: guest

iyzico:
  api:
    key: "sandbox-B1hcQfuNywDMqSBF75HrDTGUfmiJBvM3"
    secret-key: "sandbox-xB9OLSWcaTYewQGPcKIa1R24o7KQSdWP"
    base-url: "https://sandbox-api.iyzipay.com"