server:
  port: 8089

spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/address_db
    username: root
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework: DEBUG